apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{environment}}-{{appName}}
  namespace: argocd
  labels:
    App: {{appName}}
    Version: {{appVersion}}
    Project: {{project}}
spec:
  project: {{argoProject}}
  source:
    repoURL: {{gitRepoUrl}}
    targetRevision: HEAD
    path: {{environment}}

  destination:
    name: {{clusterDestination}}
    namespace: {{nameSpace}}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Force=true
      - Replace=true